name: cashnet
description: CashNet WebView App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.4+1
  webview_flutter_android: ^3.16.10
  webview_flutter_wkwebview: ^3.16.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.4
  firebase_database: ^11.3.5

  # State Management
  provider: ^6.1.2

  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image: ^4.2.0
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2

  # Video players
  youtube_player_flutter: ^9.0.4
  youtube_player_iframe: ^5.2.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: true