name: printerNet
description: 
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView
  webview_flutter: any
  webview_flutter_web: any
  webview_flutter_android: any
  webview_flutter_wkwebview: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_database: any
  cloud_functions: any

  # State Management
  provider: any

  # Image Handling
  image_picker: any
  cached_network_image: any
  image: any
  flutter_cache_manager: any
  http: any

  # Video players
  youtube_player_flutter: any
  youtube_player_iframe: any

  # UI
  cupertino_icons: any
  google_fonts: any
  flutter_svg: any

  # Utils
  intl: any
  shared_preferences: any
  timeago: any
  url_launcher: any
  flutter_linkify: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: true